### ISSUE TITLE
Model the data that we need to capture during inference runs

### ISSUE THREAD

**Issue by kartikey-vyas** [ersilia-os/model-inference-pipeline#12]
Formalise the exact fields we require to populate a metadata table. The overarching goal of the table is to capture the state of the prediction store, e.g.
- Which models have predictions
- How many (unique) predictions are available for a given model
- When were the predictions last updated
    - oldest/newest predictions?

We should also consider what kind of information about each pipeline run we want to capture:
- model details
- how was it triggered (automatic CD pipeline or manual run?)
- how long did the run take
- when was it initiated
- link to the s3 intermediary store

**Comment by nicholas-kondal** [comment]
I think the above list of data is comprehensive enough for now. Given our current plan to use Airtable as a metadata store (with S3 as an intermediary store until we've tested the connection from GitHub to Airtable), a possible data model for the metadata generated upon each inference run could look like this:

1. modelId
    - could be taken from the inference code itself

2. predsInStore
    - some sort of boolean to indicate whether or not predictions for this particular mode are present in the inference store

3. totalUniquePreds
    - number of unique predictions in the inference store i.e. the number of unique inputs for which predictions are present
    - will likely require reading from the inference store and/or S3 first via a SQL/PartiQL query or the API associated with the inference store
    - this could be used to determine predsInStore i.e. if no predictions are retrieved no predictions are stored, though this may not always be the case

4. predsLastUpdated
    - when the predictions in the inference store were last updated
    - could be taken as the earliest date from any retrieved predictions

5. pipelineLastRan
    - time that the pipeline last ran
    - could be taken as the timestamp of the current inference run once predictions finish being uploaded to the inference store or as the start time of the pipeline from the predict_parallel.yml

6. pipelineLastRanDuration
    - this may require modifying the .yml files to get the time that the GitHub action first started so that it can be passed into the inference code where it can be compared again to the time when predictions finished being uploaded to the inference store

7. s3PipelineRunsMeta
    - URL to the intermediary store in S3
    - could be generated in the pipeline using config variables and the model ID


I imagine that metadata could be generated after the predictions have been written to ensure that the data above reflects all predictions present in the inference store. To store data for each individual run, it might be worth exploring the [Splunk work](https://github.com/ersilia-os/ersilia/pull/927/files#diff-64965392109ab24f59cfd7848c73d61218fa4dc40aacca63b1e9e3a496fba5e4) done by T4SG to track these sorts of metrics + ones we might want to capture e.g. duration of each run, where it was called from (CLI, scheduled job).

Note that (from what I've seen in the inference code) a "prediction" for a particular InChI key (PK) and model ID (SK) could be present multiple times because an existing prediction is not updated if the PK and SK are already present in the inference store. Currently, there is [no batch update option available in the AWS SDK](https://aws.amazon.com/blogs/database/bulk-update-amazon-dynamodb-tables-with-aws-step-functions/), so we could use Step Functions (which might add extra complexity) or loop over each prediction to use [update_item()](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/dynamodb.html#updating-an-item) instead of put_item() (which will require a few changes to batch_writer() in the inference code).

**Comment by nicholas-kondal** [comment]
Update from 2/5 meeting with Ersilia: 

- The reference library does/will contain more than molecules, so referring to these as inputs is more appropriate

- We will have to test how costly and efficient creating and updating DynamoDB would be in the long run over other approaches such as:
          - using Athena to run SQL queries over the predictions in S3 and/or outside of it i.e. DynamoDB via a [federated query](https://docs.aws.amazon.com/athena/latest/ug/connect-to-a-data-source.html)
          - versioning the reference library

**Comment by miquelduranfrigola** [comment]
Thanks @nicholas-kondal - this is very comprehensive and I don't think we are missing anything.

Indeed, now we are talking about small molecules as inputs most of the time. Small molecules are indexed with an InChIKey. In the future, though, inputs will be of other types too (proteins, organisms, etc.). Therefore, instead of InChIKey it is better to say "Key" and instead of Molecule it is better to say "Input".
